// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sovqwlgpcyenvgspfcbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdnF3bGdwY3llbnZnc3BmY2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjAwODgsImV4cCI6MjA3MzIzNjA4OH0.HaLt6ltc1lvsA1Z_iVlDipZrPccr6hmufqw6xmNxAXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});